name: CI — Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Check
        uses: gaurav-nelson/github-action-markdown-link-check@v1

      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          globs: |
            docs/**/*.md
            README.md
